// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLrz1Yj2rYoSQ6WZL9CWZvh9p8gez9d5Q',
    appId: '1:367375712412:web:dad5e8e2dbc5b908aaad59',
    messagingSenderId: '367375712412',
    projectId: 'dindos-restaurant',
    authDomain: 'dindos-restaurant.firebaseapp.com',
    storageBucket: 'dindos-restaurant.firebasestorage.app',
    measurementId: 'G-C4GRX90S2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTBVYq1XoA7KRNCT44a2f27aFJttLSQmg',
    appId: '1:367375712412:android:b757f26172139e8baaad59',
    messagingSenderId: '367375712412',
    projectId: 'dindos-restaurant',
    storageBucket: 'dindos-restaurant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAvwY6NRjio5_7JxjCG_WMwWjF09uGONs',
    appId: '1:367375712412:ios:3d49c92d793f4fd6aaad59',
    messagingSenderId: '367375712412',
    projectId: 'dindos-restaurant',
    storageBucket: 'dindos-restaurant.firebasestorage.app',
    iosBundleId: 'com.example.dindosRestaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAvwY6NRjio5_7JxjCG_WMwWjF09uGONs',
    appId: '1:367375712412:ios:3d49c92d793f4fd6aaad59',
    messagingSenderId: '367375712412',
    projectId: 'dindos-restaurant',
    storageBucket: 'dindos-restaurant.firebasestorage.app',
    iosBundleId: 'com.example.dindosRestaurant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLrz1Yj2rYoSQ6WZL9CWZvh9p8gez9d5Q',
    appId: '1:367375712412:web:c701c5b502f4e207aaad59',
    messagingSenderId: '367375712412',
    projectId: 'dindos-restaurant',
    authDomain: 'dindos-restaurant.firebaseapp.com',
    storageBucket: 'dindos-restaurant.firebasestorage.app',
    measurementId: 'G-T05S1M79T6',
  );
}
